// <autogenerated>
//   This file was generated by dddappp code generator.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

module sui_swap_example::buy_pool_x_token_removed {

    use std::string::String;
    use sui::object::{Self, ID};
    use sui_swap_example::buy_pool::{Self, BuyPoolXTokenRemoved};

    public fun id(buy_pool_x_token_removed: &BuyPoolXTokenRemoved): object::ID {
        buy_pool::buy_pool_x_token_removed_id(buy_pool_x_token_removed)
    }

    public fun liquidity_token_id(buy_pool_x_token_removed: &BuyPoolXTokenRemoved): ID {
        buy_pool::buy_pool_x_token_removed_liquidity_token_id(buy_pool_x_token_removed)
    }

    public fun x_id(buy_pool_x_token_removed: &BuyPoolXTokenRemoved): ID {
        buy_pool::buy_pool_x_token_removed_x_id(buy_pool_x_token_removed)
    }

    public fun provider(buy_pool_x_token_removed: &BuyPoolXTokenRemoved): address {
        buy_pool::buy_pool_x_token_removed_provider(buy_pool_x_token_removed)
    }

    public fun x_token_type(buy_pool_x_token_removed: &BuyPoolXTokenRemoved): String {
        buy_pool::buy_pool_x_token_removed_x_token_type(buy_pool_x_token_removed)
    }

    public fun y_token_type(buy_pool_x_token_removed: &BuyPoolXTokenRemoved): String {
        buy_pool::buy_pool_x_token_removed_y_token_type(buy_pool_x_token_removed)
    }

    public fun x_amount(buy_pool_x_token_removed: &BuyPoolXTokenRemoved): u64 {
        buy_pool::buy_pool_x_token_removed_x_amount(buy_pool_x_token_removed)
    }

}
