// <autogenerated>
//   This file was generated by dddappp code generator.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

module sui_swap_example::buy_pool_destroyed {

    use sui::object::{Self, ID};
    use sui_swap_example::buy_pool::{Self, BuyPoolDestroyed};

    public fun id(buy_pool_destroyed: &BuyPoolDestroyed): object::ID {
        buy_pool::buy_pool_destroyed_id(buy_pool_destroyed)
    }

    public fun liquidity_token_id(buy_pool_destroyed: &BuyPoolDestroyed): ID {
        buy_pool::buy_pool_destroyed_liquidity_token_id(buy_pool_destroyed)
    }

}
