// <autogenerated>
//   This file was generated by dddappp code generator.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

module sui_swap_example::buy_pool_x_swapped_for_y {

    use std::string::String;
    use sui::object::{Self, ID};
    use sui_swap_example::buy_pool::{Self, BuyPoolXSwappedForY};

    public fun id(buy_pool_x_swapped_for_y: &BuyPoolXSwappedForY): object::ID {
        buy_pool::buy_pool_x_swapped_for_y_id(buy_pool_x_swapped_for_y)
    }

    public fun x_amount(buy_pool_x_swapped_for_y: &BuyPoolXSwappedForY): u64 {
        buy_pool::buy_pool_x_swapped_for_y_x_amount(buy_pool_x_swapped_for_y)
    }

    public fun expected_y_amount_out(buy_pool_x_swapped_for_y: &BuyPoolXSwappedForY): u64 {
        buy_pool::buy_pool_x_swapped_for_y_expected_y_amount_out(buy_pool_x_swapped_for_y)
    }

    public fun sender(buy_pool_x_swapped_for_y: &BuyPoolXSwappedForY): address {
        buy_pool::buy_pool_x_swapped_for_y_sender(buy_pool_x_swapped_for_y)
    }

    public fun x_token_type(buy_pool_x_swapped_for_y: &BuyPoolXSwappedForY): String {
        buy_pool::buy_pool_x_swapped_for_y_x_token_type(buy_pool_x_swapped_for_y)
    }

    public fun y_token_type(buy_pool_x_swapped_for_y: &BuyPoolXSwappedForY): String {
        buy_pool::buy_pool_x_swapped_for_y_y_token_type(buy_pool_x_swapped_for_y)
    }

    public fun y_amount(buy_pool_x_swapped_for_y: &BuyPoolXSwappedForY): u64 {
        buy_pool::buy_pool_x_swapped_for_y_y_amount(buy_pool_x_swapped_for_y)
    }

    public fun x_id(buy_pool_x_swapped_for_y: &BuyPoolXSwappedForY): ID {
        buy_pool::buy_pool_x_swapped_for_y_x_id(buy_pool_x_swapped_for_y)
    }

}
