// <autogenerated>
//   This file was generated by dddappp code generator.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

module sui_swap_example::buy_pool_exchange_rate_updated {

    use std::string::String;
    use sui::object::{Self, ID};
    use sui_swap_example::buy_pool::{Self, BuyPoolExchangeRateUpdated};

    public fun id(buy_pool_exchange_rate_updated: &BuyPoolExchangeRateUpdated): object::ID {
        buy_pool::buy_pool_exchange_rate_updated_id(buy_pool_exchange_rate_updated)
    }

    public fun liquidity_token_id(buy_pool_exchange_rate_updated: &BuyPoolExchangeRateUpdated): ID {
        buy_pool::buy_pool_exchange_rate_updated_liquidity_token_id(buy_pool_exchange_rate_updated)
    }

    public fun start_exchange_rate_numerator(buy_pool_exchange_rate_updated: &BuyPoolExchangeRateUpdated): u64 {
        buy_pool::buy_pool_exchange_rate_updated_start_exchange_rate_numerator(buy_pool_exchange_rate_updated)
    }

    public fun exchange_rate_numerator(buy_pool_exchange_rate_updated: &BuyPoolExchangeRateUpdated): u64 {
        buy_pool::buy_pool_exchange_rate_updated_exchange_rate_numerator(buy_pool_exchange_rate_updated)
    }

    public fun exchange_rate_denominator(buy_pool_exchange_rate_updated: &BuyPoolExchangeRateUpdated): u64 {
        buy_pool::buy_pool_exchange_rate_updated_exchange_rate_denominator(buy_pool_exchange_rate_updated)
    }

    public fun price_delta_x_amount(buy_pool_exchange_rate_updated: &BuyPoolExchangeRateUpdated): u64 {
        buy_pool::buy_pool_exchange_rate_updated_price_delta_x_amount(buy_pool_exchange_rate_updated)
    }

    public fun price_delta_numerator(buy_pool_exchange_rate_updated: &BuyPoolExchangeRateUpdated): u64 {
        buy_pool::buy_pool_exchange_rate_updated_price_delta_numerator(buy_pool_exchange_rate_updated)
    }

    public fun price_delta_denominator(buy_pool_exchange_rate_updated: &BuyPoolExchangeRateUpdated): u64 {
        buy_pool::buy_pool_exchange_rate_updated_price_delta_denominator(buy_pool_exchange_rate_updated)
    }

    public fun provider(buy_pool_exchange_rate_updated: &BuyPoolExchangeRateUpdated): address {
        buy_pool::buy_pool_exchange_rate_updated_provider(buy_pool_exchange_rate_updated)
    }

    public fun x_token_type(buy_pool_exchange_rate_updated: &BuyPoolExchangeRateUpdated): String {
        buy_pool::buy_pool_exchange_rate_updated_x_token_type(buy_pool_exchange_rate_updated)
    }

    public fun y_token_type(buy_pool_exchange_rate_updated: &BuyPoolExchangeRateUpdated): String {
        buy_pool::buy_pool_exchange_rate_updated_y_token_type(buy_pool_exchange_rate_updated)
    }

}
