// <autogenerated>
//   This file was generated by dddappp code generator.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

module sui_swap_example::buy_pool_y_reserve_deposited {

    use std::string::String;
    use sui::object::{Self, ID};
    use sui_swap_example::buy_pool::{Self, BuyPoolYReserveDeposited};

    public fun id(buy_pool_y_reserve_deposited: &BuyPoolYReserveDeposited): object::ID {
        buy_pool::buy_pool_y_reserve_deposited_id(buy_pool_y_reserve_deposited)
    }

    public fun liquidity_token_id(buy_pool_y_reserve_deposited: &BuyPoolYReserveDeposited): ID {
        buy_pool::buy_pool_y_reserve_deposited_liquidity_token_id(buy_pool_y_reserve_deposited)
    }

    public fun x_token_type(buy_pool_y_reserve_deposited: &BuyPoolYReserveDeposited): String {
        buy_pool::buy_pool_y_reserve_deposited_x_token_type(buy_pool_y_reserve_deposited)
    }

    public fun y_token_type(buy_pool_y_reserve_deposited: &BuyPoolYReserveDeposited): String {
        buy_pool::buy_pool_y_reserve_deposited_y_token_type(buy_pool_y_reserve_deposited)
    }

    public fun y_amount(buy_pool_y_reserve_deposited: &BuyPoolYReserveDeposited): u64 {
        buy_pool::buy_pool_y_reserve_deposited_y_amount(buy_pool_y_reserve_deposited)
    }

}
