// <autogenerated>
//   This file was generated by dddappp code generator.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

module sui_swap_example::buy_pool_y_reserve_withdrawn {

    use std::string::String;
    use sui::object::{Self, ID};
    use sui_swap_example::buy_pool::{Self, BuyPoolYReserveWithdrawn};

    public fun id(buy_pool_y_reserve_withdrawn: &BuyPoolYReserveWithdrawn): object::ID {
        buy_pool::buy_pool_y_reserve_withdrawn_id(buy_pool_y_reserve_withdrawn)
    }

    public fun liquidity_token_id(buy_pool_y_reserve_withdrawn: &BuyPoolYReserveWithdrawn): ID {
        buy_pool::buy_pool_y_reserve_withdrawn_liquidity_token_id(buy_pool_y_reserve_withdrawn)
    }

    public fun y_amount(buy_pool_y_reserve_withdrawn: &BuyPoolYReserveWithdrawn): u64 {
        buy_pool::buy_pool_y_reserve_withdrawn_y_amount(buy_pool_y_reserve_withdrawn)
    }

    public fun x_token_type(buy_pool_y_reserve_withdrawn: &BuyPoolYReserveWithdrawn): String {
        buy_pool::buy_pool_y_reserve_withdrawn_x_token_type(buy_pool_y_reserve_withdrawn)
    }

    public fun y_token_type(buy_pool_y_reserve_withdrawn: &BuyPoolYReserveWithdrawn): String {
        buy_pool::buy_pool_y_reserve_withdrawn_y_token_type(buy_pool_y_reserve_withdrawn)
    }

}
