// <autogenerated>
//   This file was generated by dddappp code generator.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

module sui_swap_example::buy_pool_added_to_exchange {

    use std::string::String;
    use sui::object::{Self, ID};
    use sui_swap_example::exchange::{Self, BuyPoolAddedToExchange};

    public fun id(buy_pool_added_to_exchange: &BuyPoolAddedToExchange): object::ID {
        exchange::buy_pool_added_to_exchange_id(buy_pool_added_to_exchange)
    }

    public fun buy_pool_id(buy_pool_added_to_exchange: &BuyPoolAddedToExchange): ID {
        exchange::buy_pool_added_to_exchange_buy_pool_id(buy_pool_added_to_exchange)
    }

    public fun x_token_type(buy_pool_added_to_exchange: &BuyPoolAddedToExchange): String {
        exchange::buy_pool_added_to_exchange_x_token_type(buy_pool_added_to_exchange)
    }

    public fun y_token_type(buy_pool_added_to_exchange: &BuyPoolAddedToExchange): String {
        exchange::buy_pool_added_to_exchange_y_token_type(buy_pool_added_to_exchange)
    }

}
