// <autogenerated>
//   This file was generated by dddappp code generator.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

module sui_swap_example::buy_pool_initialized {

    use std::option::{Self, Option};
    use std::string::String;
    use sui::object::{Self, ID};
    use sui_swap_example::trade_pool::{Self, BuyPoolInitialized};

    public fun id(buy_pool_initialized: &BuyPoolInitialized): option::Option<object::ID> {
        trade_pool::buy_pool_initialized_id(buy_pool_initialized)
    }

    public fun exchange_id(buy_pool_initialized: &BuyPoolInitialized): ID {
        trade_pool::buy_pool_initialized_exchange_id(buy_pool_initialized)
    }

    public fun exchange_rate_numerator(buy_pool_initialized: &BuyPoolInitialized): u64 {
        trade_pool::buy_pool_initialized_exchange_rate_numerator(buy_pool_initialized)
    }

    public fun exchange_rate_denominator(buy_pool_initialized: &BuyPoolInitialized): u64 {
        trade_pool::buy_pool_initialized_exchange_rate_denominator(buy_pool_initialized)
    }

    public fun price_curve_type(buy_pool_initialized: &BuyPoolInitialized): u8 {
        trade_pool::buy_pool_initialized_price_curve_type(buy_pool_initialized)
    }

    public fun price_delta_x_amount(buy_pool_initialized: &BuyPoolInitialized): u64 {
        trade_pool::buy_pool_initialized_price_delta_x_amount(buy_pool_initialized)
    }

    public fun price_delta_numerator(buy_pool_initialized: &BuyPoolInitialized): u64 {
        trade_pool::buy_pool_initialized_price_delta_numerator(buy_pool_initialized)
    }

    public fun price_delta_denominator(buy_pool_initialized: &BuyPoolInitialized): u64 {
        trade_pool::buy_pool_initialized_price_delta_denominator(buy_pool_initialized)
    }

    public fun provider(buy_pool_initialized: &BuyPoolInitialized): address {
        trade_pool::buy_pool_initialized_provider(buy_pool_initialized)
    }

    public fun x_token_type(buy_pool_initialized: &BuyPoolInitialized): String {
        trade_pool::buy_pool_initialized_x_token_type(buy_pool_initialized)
    }

    public fun y_token_type(buy_pool_initialized: &BuyPoolInitialized): String {
        trade_pool::buy_pool_initialized_y_token_type(buy_pool_initialized)
    }

    public fun y_amount(buy_pool_initialized: &BuyPoolInitialized): u64 {
        trade_pool::buy_pool_initialized_y_amount(buy_pool_initialized)
    }

    public fun liquidity_token_id(buy_pool_initialized: &BuyPoolInitialized): Option<ID> {
        trade_pool::buy_pool_initialized_liquidity_token_id(buy_pool_initialized)
    }

}
