// <autogenerated>
//   This file was generated by dddappp code generator.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

module sui_swap_core::exchange_aggregate {
    use std::string::String;
    use sui::object::ID;
    use sui::tx_context;
    use sui_swap_core::exchange;
    use sui_swap_core::exchange_add_buy_pool_logic;
    use sui_swap_core::exchange_add_sell_pool_logic;
    use sui_swap_core::exchange_add_token_pair_logic;
    use sui_swap_core::exchange_add_trade_pool_logic;
    use sui_swap_core::exchange_update_logic;

    friend sui_swap_core::token_pair_initialize_liquidity_logic;
    friend sui_swap_core::trade_pool_initialize_trade_pool_logic;
    friend sui_swap_core::trade_pool_initialize_sell_pool_logic;
    friend sui_swap_core::trade_pool_initialize_buy_pool_logic;
    friend sui_swap_core::token_pair_service;
    friend sui_swap_core::token_pair_service_process;
    friend sui_swap_core::trade_pool_service;
    friend sui_swap_core::sell_pool_service;
    friend sui_swap_core::trade_pool_service_process;
    friend sui_swap_core::sell_pool_service_process;
    friend sui_swap_core::buy_pool_service;
    friend sui_swap_core::buy_pool_service_process;
    friend sui_swap_core::nft_service;

    const EInvalidAdminCap: u64 = 50;

    #[allow(unused_mut_parameter)]
    public(friend) fun add_token_pair<X: key + store, Y>(
        exchange: &mut exchange::Exchange,
        token_pair_id: ID,
        ctx: &mut tx_context::TxContext,
    ) {
        exchange::assert_schema_version(exchange);
        let token_pair_added_to_exchange = exchange_add_token_pair_logic::verify<X, Y>(
            token_pair_id,
            exchange,
            ctx,
        );
        exchange_add_token_pair_logic::mutate<X, Y>(
            &token_pair_added_to_exchange,
            exchange,
            ctx,
        );
        exchange::update_object_version(exchange);
        exchange::emit_token_pair_added_to_exchange(token_pair_added_to_exchange);
    }

    #[allow(unused_mut_parameter)]
    public(friend) fun add_trade_pool<X: key + store, Y>(
        exchange: &mut exchange::Exchange,
        trade_pool_id: ID,
        ctx: &mut tx_context::TxContext,
    ) {
        exchange::assert_schema_version(exchange);
        let trade_pool_added_to_exchange = exchange_add_trade_pool_logic::verify<X, Y>(
            trade_pool_id,
            exchange,
            ctx,
        );
        exchange_add_trade_pool_logic::mutate<X, Y>(
            &trade_pool_added_to_exchange,
            exchange,
            ctx,
        );
        exchange::update_object_version(exchange);
        exchange::emit_trade_pool_added_to_exchange(trade_pool_added_to_exchange);
    }

    #[allow(unused_mut_parameter)]
    public(friend) fun add_sell_pool<X: key + store, Y>(
        exchange: &mut exchange::Exchange,
        sell_pool_id: ID,
        ctx: &mut tx_context::TxContext,
    ) {
        exchange::assert_schema_version(exchange);
        let sell_pool_added_to_exchange = exchange_add_sell_pool_logic::verify<X, Y>(
            sell_pool_id,
            exchange,
            ctx,
        );
        exchange_add_sell_pool_logic::mutate<X, Y>(
            &sell_pool_added_to_exchange,
            exchange,
            ctx,
        );
        exchange::update_object_version(exchange);
        exchange::emit_sell_pool_added_to_exchange(sell_pool_added_to_exchange);
    }

    #[allow(unused_mut_parameter)]
    public(friend) fun add_buy_pool<X: key + store, Y>(
        exchange: &mut exchange::Exchange,
        buy_pool_id: ID,
        ctx: &mut tx_context::TxContext,
    ) {
        exchange::assert_schema_version(exchange);
        let buy_pool_added_to_exchange = exchange_add_buy_pool_logic::verify<X, Y>(
            buy_pool_id,
            exchange,
            ctx,
        );
        exchange_add_buy_pool_logic::mutate<X, Y>(
            &buy_pool_added_to_exchange,
            exchange,
            ctx,
        );
        exchange::update_object_version(exchange);
        exchange::emit_buy_pool_added_to_exchange(buy_pool_added_to_exchange);
    }

    public entry fun update(
        exchange: &mut exchange::Exchange,
        admin_cap: &exchange::AdminCap,
        name: String,
        update_token_pairs: bool,
        token_pairs: vector<ID>,
        token_pair_x_token_types: vector<String>,
        token_pair_y_token_types: vector<String>,
        update_trade_pools: bool,
        trade_pools: vector<ID>,
        trade_pool_x_token_types: vector<String>,
        trade_pool_y_token_types: vector<String>,
        update_sell_pools: bool,
        sell_pools: vector<ID>,
        sell_pool_x_token_types: vector<String>,
        sell_pool_y_token_types: vector<String>,
        update_buy_pools: bool,
        buy_pools: vector<ID>,
        buy_pool_x_token_types: vector<String>,
        buy_pool_y_token_types: vector<String>,
        ctx: &mut tx_context::TxContext,
    ) {
        assert!(exchange::admin_cap(exchange) == sui::object::id(admin_cap), EInvalidAdminCap);
        exchange::assert_schema_version(exchange);
        let exchange_updated = exchange_update_logic::verify(
            name,
            update_token_pairs,
            token_pairs,
            token_pair_x_token_types,
            token_pair_y_token_types,
            update_trade_pools,
            trade_pools,
            trade_pool_x_token_types,
            trade_pool_y_token_types,
            update_sell_pools,
            sell_pools,
            sell_pool_x_token_types,
            sell_pool_y_token_types,
            update_buy_pools,
            buy_pools,
            buy_pool_x_token_types,
            buy_pool_y_token_types,
            exchange,
            ctx,
        );
        exchange_update_logic::mutate(
            &exchange_updated,
            exchange,
            ctx,
        );
        exchange::update_object_version(exchange);
        exchange::emit_exchange_updated(exchange_updated);
    }

}
