// <autogenerated>
//   This file was generated by dddappp code generator.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

module sui_swap_example::fee_rate_updated {

    use sui::object::{Self, ID};
    use sui_swap_example::token_pair::{Self, FeeRateUpdated};

    public fun id(fee_rate_updated: &FeeRateUpdated): object::ID {
        token_pair::fee_rate_updated_id(fee_rate_updated)
    }

    public fun liquidity_token_id(fee_rate_updated: &FeeRateUpdated): ID {
        token_pair::fee_rate_updated_liquidity_token_id(fee_rate_updated)
    }

    public fun fee_numerator(fee_rate_updated: &FeeRateUpdated): u64 {
        token_pair::fee_rate_updated_fee_numerator(fee_rate_updated)
    }

    public fun fee_denominator(fee_rate_updated: &FeeRateUpdated): u64 {
        token_pair::fee_rate_updated_fee_denominator(fee_rate_updated)
    }

}
