// <autogenerated>
//   This file was generated by dddappp code generator.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

//
// Mint event module is disabled.
// Use liquidity_token module instead.
//
