// <autogenerated>
//   This file was generated by dddappp code generator.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

module sui_swap_example::liquidity_removed {

    use std::string::String;
    use sui::object::{Self, ID};
    use sui_swap_example::token_pair::{Self, LiquidityRemoved};

    public fun id(liquidity_removed: &LiquidityRemoved): object::ID {
        token_pair::liquidity_removed_id(liquidity_removed)
    }

    public fun liquidity_token_id(liquidity_removed: &LiquidityRemoved): ID {
        token_pair::liquidity_removed_liquidity_token_id(liquidity_removed)
    }

    public fun x_id(liquidity_removed: &LiquidityRemoved): ID {
        token_pair::liquidity_removed_x_id(liquidity_removed)
    }

    public fun provider(liquidity_removed: &LiquidityRemoved): address {
        token_pair::liquidity_removed_provider(liquidity_removed)
    }

    public fun x_token_type(liquidity_removed: &LiquidityRemoved): String {
        token_pair::liquidity_removed_x_token_type(liquidity_removed)
    }

    public fun y_token_type(liquidity_removed: &LiquidityRemoved): String {
        token_pair::liquidity_removed_y_token_type(liquidity_removed)
    }

    public fun x_amount(liquidity_removed: &LiquidityRemoved): u64 {
        token_pair::liquidity_removed_x_amount(liquidity_removed)
    }

    public fun y_amount(liquidity_removed: &LiquidityRemoved): u64 {
        token_pair::liquidity_removed_y_amount(liquidity_removed)
    }

    public fun liquidity_amount(liquidity_removed: &LiquidityRemoved): u64 {
        token_pair::liquidity_removed_liquidity_amount(liquidity_removed)
    }

}
