// <autogenerated>
//   This file was generated by dddappp code generator.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

module sui_swap_example::pool_destroyed {

    use sui::object::{Self, ID};
    use sui_swap_example::trade_pool::{Self, PoolDestroyed};

    public fun id(pool_destroyed: &PoolDestroyed): object::ID {
        trade_pool::pool_destroyed_id(pool_destroyed)
    }

    public fun liquidity_token_id(pool_destroyed: &PoolDestroyed): ID {
        trade_pool::pool_destroyed_liquidity_token_id(pool_destroyed)
    }

}
