// <autogenerated>
//   This file was generated by dddappp code generator.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

module sui_swap_example::pool_x_token_added {

    use std::string::String;
    use sui::object::{Self, ID};
    use sui_swap_example::trade_pool::{Self, PoolXTokenAdded};

    public fun id(pool_x_token_added: &PoolXTokenAdded): object::ID {
        trade_pool::pool_x_token_added_id(pool_x_token_added)
    }

    public fun liquidity_token_id(pool_x_token_added: &PoolXTokenAdded): ID {
        trade_pool::pool_x_token_added_liquidity_token_id(pool_x_token_added)
    }

    public fun x_amount(pool_x_token_added: &PoolXTokenAdded): u64 {
        trade_pool::pool_x_token_added_x_amount(pool_x_token_added)
    }

    public fun provider(pool_x_token_added: &PoolXTokenAdded): address {
        trade_pool::pool_x_token_added_provider(pool_x_token_added)
    }

    public fun x_token_type(pool_x_token_added: &PoolXTokenAdded): String {
        trade_pool::pool_x_token_added_x_token_type(pool_x_token_added)
    }

    public fun y_token_type(pool_x_token_added: &PoolXTokenAdded): String {
        trade_pool::pool_x_token_added_y_token_type(pool_x_token_added)
    }

    public fun x_id(pool_x_token_added: &PoolXTokenAdded): ID {
        trade_pool::pool_x_token_added_x_id(pool_x_token_added)
    }

}
