// <autogenerated>
//   This file was generated by dddappp code generator.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

module sui_swap_core::pool_type {
    use std::vector;

    public fun trade_pool(): u8 {
        0
    }

    public fun sell_pool(): u8 {
        1
    }

    public fun buy_pool(): u8 {
        2
    }

    public fun is_valid(v: u8): bool {
        v == trade_pool() || v == sell_pool() || v == buy_pool()
    }

    public fun are_all_valid(vs: &vector<u8>): bool {
        let i = 0;
        let l = vector::length(vs);
        while (i < l) {
            if (!is_valid(*vector::borrow(vs, i))) {
                return false
            };
            i = i + 1;
        };
        true
    }
}
