// <autogenerated>
//   This file was generated by dddappp code generator.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

module sui_swap_core::pool_y_reserve_deposited {

    use std::string::String;
    use sui::object::{Self, ID};
    use sui_swap_core::trade_pool::{Self, PoolYReserveDeposited};

    public fun id(pool_y_reserve_deposited: &PoolYReserveDeposited): object::ID {
        trade_pool::pool_y_reserve_deposited_id(pool_y_reserve_deposited)
    }

    public fun liquidity_token_id(pool_y_reserve_deposited: &PoolYReserveDeposited): ID {
        trade_pool::pool_y_reserve_deposited_liquidity_token_id(pool_y_reserve_deposited)
    }

    public fun x_token_type(pool_y_reserve_deposited: &PoolYReserveDeposited): String {
        trade_pool::pool_y_reserve_deposited_x_token_type(pool_y_reserve_deposited)
    }

    public fun y_token_type(pool_y_reserve_deposited: &PoolYReserveDeposited): String {
        trade_pool::pool_y_reserve_deposited_y_token_type(pool_y_reserve_deposited)
    }

    public fun y_amount(pool_y_reserve_deposited: &PoolYReserveDeposited): u64 {
        trade_pool::pool_y_reserve_deposited_y_amount(pool_y_reserve_deposited)
    }

}
