// <autogenerated>
//   This file was generated by dddappp code generator.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

module sui_swap_example::pool_y_swapped_for_x {

    use std::string::String;
    use sui::object::{Self, ID};
    use sui_swap_example::trade_pool::{Self, PoolYSwappedForX};

    public fun id(pool_y_swapped_for_x: &PoolYSwappedForX): object::ID {
        trade_pool::pool_y_swapped_for_x_id(pool_y_swapped_for_x)
    }

    public fun x_id(pool_y_swapped_for_x: &PoolYSwappedForX): ID {
        trade_pool::pool_y_swapped_for_x_x_id(pool_y_swapped_for_x)
    }

    public fun sender(pool_y_swapped_for_x: &PoolYSwappedForX): address {
        trade_pool::pool_y_swapped_for_x_sender(pool_y_swapped_for_x)
    }

    public fun x_token_type(pool_y_swapped_for_x: &PoolYSwappedForX): String {
        trade_pool::pool_y_swapped_for_x_x_token_type(pool_y_swapped_for_x)
    }

    public fun y_token_type(pool_y_swapped_for_x: &PoolYSwappedForX): String {
        trade_pool::pool_y_swapped_for_x_y_token_type(pool_y_swapped_for_x)
    }

    public fun x_amount(pool_y_swapped_for_x: &PoolYSwappedForX): u64 {
        trade_pool::pool_y_swapped_for_x_x_amount(pool_y_swapped_for_x)
    }

    public fun y_amount(pool_y_swapped_for_x: &PoolYSwappedForX): u64 {
        trade_pool::pool_y_swapped_for_x_y_amount(pool_y_swapped_for_x)
    }

    public fun new_exchange_rate_numerator(pool_y_swapped_for_x: &PoolYSwappedForX): u64 {
        trade_pool::pool_y_swapped_for_x_new_exchange_rate_numerator(pool_y_swapped_for_x)
    }

}
