// <autogenerated>
//   This file was generated by dddappp code generator.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

module sui_swap_example::pool_y_reserve_withdrawn {

    use std::string::String;
    use sui::object::{Self, ID};
    use sui_swap_example::trade_pool::{Self, PoolYReserveWithdrawn};

    public fun id(pool_y_reserve_withdrawn: &PoolYReserveWithdrawn): object::ID {
        trade_pool::pool_y_reserve_withdrawn_id(pool_y_reserve_withdrawn)
    }

    public fun liquidity_token_id(pool_y_reserve_withdrawn: &PoolYReserveWithdrawn): ID {
        trade_pool::pool_y_reserve_withdrawn_liquidity_token_id(pool_y_reserve_withdrawn)
    }

    public fun y_amount(pool_y_reserve_withdrawn: &PoolYReserveWithdrawn): u64 {
        trade_pool::pool_y_reserve_withdrawn_y_amount(pool_y_reserve_withdrawn)
    }

    public fun x_token_type(pool_y_reserve_withdrawn: &PoolYReserveWithdrawn): String {
        trade_pool::pool_y_reserve_withdrawn_x_token_type(pool_y_reserve_withdrawn)
    }

    public fun y_token_type(pool_y_reserve_withdrawn: &PoolYReserveWithdrawn): String {
        trade_pool::pool_y_reserve_withdrawn_y_token_type(pool_y_reserve_withdrawn)
    }

}
