// <autogenerated>
//   This file was generated by dddappp code generator.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

module sui_swap_example::sell_pool_exchange_rate_updated {

    use std::string::String;
    use sui::object::{Self, ID};
    use sui_swap_example::sell_pool::{Self, SellPoolExchangeRateUpdated};

    public fun id(sell_pool_exchange_rate_updated: &SellPoolExchangeRateUpdated): object::ID {
        sell_pool::sell_pool_exchange_rate_updated_id(sell_pool_exchange_rate_updated)
    }

    public fun liquidity_token_id(sell_pool_exchange_rate_updated: &SellPoolExchangeRateUpdated): ID {
        sell_pool::sell_pool_exchange_rate_updated_liquidity_token_id(sell_pool_exchange_rate_updated)
    }

    public fun start_exchange_rate_numerator(sell_pool_exchange_rate_updated: &SellPoolExchangeRateUpdated): u64 {
        sell_pool::sell_pool_exchange_rate_updated_start_exchange_rate_numerator(sell_pool_exchange_rate_updated)
    }

    public fun exchange_rate_numerator(sell_pool_exchange_rate_updated: &SellPoolExchangeRateUpdated): u64 {
        sell_pool::sell_pool_exchange_rate_updated_exchange_rate_numerator(sell_pool_exchange_rate_updated)
    }

    public fun exchange_rate_denominator(sell_pool_exchange_rate_updated: &SellPoolExchangeRateUpdated): u64 {
        sell_pool::sell_pool_exchange_rate_updated_exchange_rate_denominator(sell_pool_exchange_rate_updated)
    }

    public fun price_delta_x_amount(sell_pool_exchange_rate_updated: &SellPoolExchangeRateUpdated): u64 {
        sell_pool::sell_pool_exchange_rate_updated_price_delta_x_amount(sell_pool_exchange_rate_updated)
    }

    public fun price_delta_numerator(sell_pool_exchange_rate_updated: &SellPoolExchangeRateUpdated): u64 {
        sell_pool::sell_pool_exchange_rate_updated_price_delta_numerator(sell_pool_exchange_rate_updated)
    }

    public fun price_delta_denominator(sell_pool_exchange_rate_updated: &SellPoolExchangeRateUpdated): u64 {
        sell_pool::sell_pool_exchange_rate_updated_price_delta_denominator(sell_pool_exchange_rate_updated)
    }

    public fun provider(sell_pool_exchange_rate_updated: &SellPoolExchangeRateUpdated): address {
        sell_pool::sell_pool_exchange_rate_updated_provider(sell_pool_exchange_rate_updated)
    }

    public fun x_token_type(sell_pool_exchange_rate_updated: &SellPoolExchangeRateUpdated): String {
        sell_pool::sell_pool_exchange_rate_updated_x_token_type(sell_pool_exchange_rate_updated)
    }

    public fun y_token_type(sell_pool_exchange_rate_updated: &SellPoolExchangeRateUpdated): String {
        sell_pool::sell_pool_exchange_rate_updated_y_token_type(sell_pool_exchange_rate_updated)
    }

}
