// <autogenerated>
//   This file was generated by dddappp code generator.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

module sui_swap_example::sell_pool_y_reserve_withdrawn {

    use std::string::String;
    use sui::object::{Self, ID};
    use sui_swap_example::sell_pool::{Self, SellPoolYReserveWithdrawn};

    public fun id(sell_pool_y_reserve_withdrawn: &SellPoolYReserveWithdrawn): object::ID {
        sell_pool::sell_pool_y_reserve_withdrawn_id(sell_pool_y_reserve_withdrawn)
    }

    public fun liquidity_token_id(sell_pool_y_reserve_withdrawn: &SellPoolYReserveWithdrawn): ID {
        sell_pool::sell_pool_y_reserve_withdrawn_liquidity_token_id(sell_pool_y_reserve_withdrawn)
    }

    public fun y_amount(sell_pool_y_reserve_withdrawn: &SellPoolYReserveWithdrawn): u64 {
        sell_pool::sell_pool_y_reserve_withdrawn_y_amount(sell_pool_y_reserve_withdrawn)
    }

    public fun x_token_type(sell_pool_y_reserve_withdrawn: &SellPoolYReserveWithdrawn): String {
        sell_pool::sell_pool_y_reserve_withdrawn_x_token_type(sell_pool_y_reserve_withdrawn)
    }

    public fun y_token_type(sell_pool_y_reserve_withdrawn: &SellPoolYReserveWithdrawn): String {
        sell_pool::sell_pool_y_reserve_withdrawn_y_token_type(sell_pool_y_reserve_withdrawn)
    }

}
