// <autogenerated>
//   This file was generated by dddappp code generator.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

module sui_swap_example::sell_pool_y_swapped_for_x {

    use std::string::String;
    use sui::object::{Self, ID};
    use sui_swap_example::sell_pool::{Self, SellPoolYSwappedForX};

    public fun id(sell_pool_y_swapped_for_x: &SellPoolYSwappedForX): object::ID {
        sell_pool::sell_pool_y_swapped_for_x_id(sell_pool_y_swapped_for_x)
    }

    public fun x_id(sell_pool_y_swapped_for_x: &SellPoolYSwappedForX): ID {
        sell_pool::sell_pool_y_swapped_for_x_x_id(sell_pool_y_swapped_for_x)
    }

    public fun sender(sell_pool_y_swapped_for_x: &SellPoolYSwappedForX): address {
        sell_pool::sell_pool_y_swapped_for_x_sender(sell_pool_y_swapped_for_x)
    }

    public fun x_token_type(sell_pool_y_swapped_for_x: &SellPoolYSwappedForX): String {
        sell_pool::sell_pool_y_swapped_for_x_x_token_type(sell_pool_y_swapped_for_x)
    }

    public fun y_token_type(sell_pool_y_swapped_for_x: &SellPoolYSwappedForX): String {
        sell_pool::sell_pool_y_swapped_for_x_y_token_type(sell_pool_y_swapped_for_x)
    }

    public fun x_amount(sell_pool_y_swapped_for_x: &SellPoolYSwappedForX): u64 {
        sell_pool::sell_pool_y_swapped_for_x_x_amount(sell_pool_y_swapped_for_x)
    }

    public fun y_amount(sell_pool_y_swapped_for_x: &SellPoolYSwappedForX): u64 {
        sell_pool::sell_pool_y_swapped_for_x_y_amount(sell_pool_y_swapped_for_x)
    }

    public fun new_exchange_rate_numerator(sell_pool_y_swapped_for_x: &SellPoolYSwappedForX): u64 {
        sell_pool::sell_pool_y_swapped_for_x_new_exchange_rate_numerator(sell_pool_y_swapped_for_x)
    }

}
