// <autogenerated>
//   This file was generated by dddappp code generator.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

module sui_swap_example::sell_pool_added_to_exchange {

    use std::string::String;
    use sui::object::{Self, ID};
    use sui_swap_example::exchange::{Self, SellPoolAddedToExchange};

    public fun id(sell_pool_added_to_exchange: &SellPoolAddedToExchange): object::ID {
        exchange::sell_pool_added_to_exchange_id(sell_pool_added_to_exchange)
    }

    public fun sell_pool_id(sell_pool_added_to_exchange: &SellPoolAddedToExchange): ID {
        exchange::sell_pool_added_to_exchange_sell_pool_id(sell_pool_added_to_exchange)
    }

    public fun x_token_type(sell_pool_added_to_exchange: &SellPoolAddedToExchange): String {
        exchange::sell_pool_added_to_exchange_x_token_type(sell_pool_added_to_exchange)
    }

    public fun y_token_type(sell_pool_added_to_exchange: &SellPoolAddedToExchange): String {
        exchange::sell_pool_added_to_exchange_y_token_type(sell_pool_added_to_exchange)
    }

}
