// <autogenerated>
//   This file was generated by dddappp code generator.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

module sui_swap_example::sell_pool_x_token_removed {

    use std::string::String;
    use sui::object::{Self, ID};
    use sui_swap_example::sell_pool::{Self, SellPoolXTokenRemoved};

    public fun id(sell_pool_x_token_removed: &SellPoolXTokenRemoved): object::ID {
        sell_pool::sell_pool_x_token_removed_id(sell_pool_x_token_removed)
    }

    public fun liquidity_token_id(sell_pool_x_token_removed: &SellPoolXTokenRemoved): ID {
        sell_pool::sell_pool_x_token_removed_liquidity_token_id(sell_pool_x_token_removed)
    }

    public fun x_id(sell_pool_x_token_removed: &SellPoolXTokenRemoved): ID {
        sell_pool::sell_pool_x_token_removed_x_id(sell_pool_x_token_removed)
    }

    public fun provider(sell_pool_x_token_removed: &SellPoolXTokenRemoved): address {
        sell_pool::sell_pool_x_token_removed_provider(sell_pool_x_token_removed)
    }

    public fun x_token_type(sell_pool_x_token_removed: &SellPoolXTokenRemoved): String {
        sell_pool::sell_pool_x_token_removed_x_token_type(sell_pool_x_token_removed)
    }

    public fun y_token_type(sell_pool_x_token_removed: &SellPoolXTokenRemoved): String {
        sell_pool::sell_pool_x_token_removed_y_token_type(sell_pool_x_token_removed)
    }

    public fun x_amount(sell_pool_x_token_removed: &SellPoolXTokenRemoved): u64 {
        sell_pool::sell_pool_x_token_removed_x_amount(sell_pool_x_token_removed)
    }

}
