// <autogenerated>
//   This file was generated by dddappp code generator.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

module sui_swap_example::sell_pool_x_token_added {

    use std::string::String;
    use sui::object::{Self, ID};
    use sui_swap_example::sell_pool::{Self, SellPoolXTokenAdded};

    public fun id(sell_pool_x_token_added: &SellPoolXTokenAdded): object::ID {
        sell_pool::sell_pool_x_token_added_id(sell_pool_x_token_added)
    }

    public fun liquidity_token_id(sell_pool_x_token_added: &SellPoolXTokenAdded): ID {
        sell_pool::sell_pool_x_token_added_liquidity_token_id(sell_pool_x_token_added)
    }

    public fun x_amount(sell_pool_x_token_added: &SellPoolXTokenAdded): u64 {
        sell_pool::sell_pool_x_token_added_x_amount(sell_pool_x_token_added)
    }

    public fun provider(sell_pool_x_token_added: &SellPoolXTokenAdded): address {
        sell_pool::sell_pool_x_token_added_provider(sell_pool_x_token_added)
    }

    public fun x_token_type(sell_pool_x_token_added: &SellPoolXTokenAdded): String {
        sell_pool::sell_pool_x_token_added_x_token_type(sell_pool_x_token_added)
    }

    public fun y_token_type(sell_pool_x_token_added: &SellPoolXTokenAdded): String {
        sell_pool::sell_pool_x_token_added_y_token_type(sell_pool_x_token_added)
    }

    public fun x_id(sell_pool_x_token_added: &SellPoolXTokenAdded): ID {
        sell_pool::sell_pool_x_token_added_x_id(sell_pool_x_token_added)
    }

}
