// <autogenerated>
//   This file was generated by dddappp code generator.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

module sui_swap_example::sell_pool_destroyed {

    use sui::object::{Self, ID};
    use sui_swap_example::sell_pool::{Self, SellPoolDestroyed};

    public fun id(sell_pool_destroyed: &SellPoolDestroyed): object::ID {
        sell_pool::sell_pool_destroyed_id(sell_pool_destroyed)
    }

    public fun liquidity_token_id(sell_pool_destroyed: &SellPoolDestroyed): ID {
        sell_pool::sell_pool_destroyed_liquidity_token_id(sell_pool_destroyed)
    }

}
