// <autogenerated>
//   This file was generated by dddappp code generator.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

module sui_swap_example::token_pair_destroyed {

    use sui::object::{Self, ID};
    use sui_swap_example::token_pair::{Self, TokenPairDestroyed};

    public fun id(token_pair_destroyed: &TokenPairDestroyed): object::ID {
        token_pair::token_pair_destroyed_id(token_pair_destroyed)
    }

    public fun liquidity_token_id(token_pair_destroyed: &TokenPairDestroyed): ID {
        token_pair::token_pair_destroyed_liquidity_token_id(token_pair_destroyed)
    }

}
