// <autogenerated>
//   This file was generated by dddappp code generator.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

module sui_swap_example::trade_pool_aggregate {
    use sui::balance::Balance;
    use sui::object::ID;
    use sui::tx_context;
    use sui_swap_example::exchange::Exchange;
    use sui_swap_example::liquidity_token::LiquidityToken;
    use sui_swap_example::trade_pool;
    use sui_swap_example::trade_pool_add_x_token_logic;
    use sui_swap_example::trade_pool_buy_x_logic;
    use sui_swap_example::trade_pool_deposit_y_reserve_logic;
    use sui_swap_example::trade_pool_destroy_logic;
    use sui_swap_example::trade_pool_initialize_buy_pool_logic;
    use sui_swap_example::trade_pool_initialize_sell_pool_logic;
    use sui_swap_example::trade_pool_initialize_trade_pool_logic;
    use sui_swap_example::trade_pool_remove_x_token_logic;
    use sui_swap_example::trade_pool_sell_x_logic;
    use sui_swap_example::trade_pool_update_exchange_rate_logic;
    use sui_swap_example::trade_pool_withdraw_y_reserve_logic;

    friend sui_swap_example::token_pair_service;
    friend sui_swap_example::token_pair_service_process;
    friend sui_swap_example::trade_pool_service;
    friend sui_swap_example::sell_pool_service;
    friend sui_swap_example::trade_pool_service_process;
    friend sui_swap_example::sell_pool_service_process;
    friend sui_swap_example::buy_pool_service;
    friend sui_swap_example::buy_pool_service_process;
    friend sui_swap_example::nft_service;

    #[allow(unused_mut_parameter)]
    public(friend) fun initialize_trade_pool<X: key + store, Y>(
        exchange: &mut Exchange,
        x: X,
        x_amount: u64,
        y_amount: Balance<Y>,
        exchange_rate_numerator: u64,
        exchange_rate_denominator: u64,
        price_curve_type: u8,
        price_delta_x_amount: u64,
        price_delta_numerator: u64,
        price_delta_denominator: u64,
        ctx: &mut tx_context::TxContext,
    ): (trade_pool::TradePool<X, Y>, LiquidityToken<X, Y>) {
        let trade_pool_initialized = trade_pool_initialize_trade_pool_logic::verify<X, Y>(
            exchange,
            &x,
            x_amount,
            &y_amount,
            exchange_rate_numerator,
            exchange_rate_denominator,
            price_curve_type,
            price_delta_x_amount,
            price_delta_numerator,
            price_delta_denominator,
            ctx,
        );
        let (trade_pool, liquidity_token) = trade_pool_initialize_trade_pool_logic::mutate<X, Y>(
            &mut trade_pool_initialized,
            x,
            y_amount,
            exchange,
            ctx,
        );
        trade_pool::set_trade_pool_initialized_id(&mut trade_pool_initialized, trade_pool::id(&trade_pool));
        trade_pool::emit_trade_pool_initialized(trade_pool_initialized);
        (trade_pool, liquidity_token)
    }

    #[allow(unused_mut_parameter)]
    public(friend) fun initialize_sell_pool<X: key + store, Y>(
        exchange: &mut Exchange,
        x: X,
        x_amount: u64,
        exchange_rate_numerator: u64,
        exchange_rate_denominator: u64,
        price_curve_type: u8,
        price_delta_x_amount: u64,
        price_delta_numerator: u64,
        price_delta_denominator: u64,
        ctx: &mut tx_context::TxContext,
    ): (trade_pool::TradePool<X, Y>, LiquidityToken<X, Y>) {
        let sell_pool_initialized = trade_pool_initialize_sell_pool_logic::verify<X, Y>(
            exchange,
            &x,
            x_amount,
            exchange_rate_numerator,
            exchange_rate_denominator,
            price_curve_type,
            price_delta_x_amount,
            price_delta_numerator,
            price_delta_denominator,
            ctx,
        );
        let (trade_pool, liquidity_token) = trade_pool_initialize_sell_pool_logic::mutate<X, Y>(
            &mut sell_pool_initialized,
            x,
            exchange,
            ctx,
        );
        trade_pool::set_sell_pool_initialized_id(&mut sell_pool_initialized, trade_pool::id(&trade_pool));
        trade_pool::emit_sell_pool_initialized(sell_pool_initialized);
        (trade_pool, liquidity_token)
    }

    #[allow(unused_mut_parameter)]
    public fun initialize_buy_pool<X: key + store, Y>(
        exchange: &mut Exchange,
        y_amount: Balance<Y>,
        exchange_rate_numerator: u64,
        exchange_rate_denominator: u64,
        price_curve_type: u8,
        price_delta_x_amount: u64,
        price_delta_numerator: u64,
        price_delta_denominator: u64,
        ctx: &mut tx_context::TxContext,
    ): (trade_pool::TradePool<X, Y>, LiquidityToken<X, Y>) {
        let buy_pool_initialized = trade_pool_initialize_buy_pool_logic::verify<X, Y>(
            exchange,
            &y_amount,
            exchange_rate_numerator,
            exchange_rate_denominator,
            price_curve_type,
            price_delta_x_amount,
            price_delta_numerator,
            price_delta_denominator,
            ctx,
        );
        let (trade_pool, liquidity_token) = trade_pool_initialize_buy_pool_logic::mutate<X, Y>(
            &mut buy_pool_initialized,
            y_amount,
            exchange,
            ctx,
        );
        trade_pool::set_buy_pool_initialized_id(&mut buy_pool_initialized, trade_pool::id(&trade_pool));
        trade_pool::emit_buy_pool_initialized(buy_pool_initialized);
        (trade_pool, liquidity_token)
    }

    #[allow(unused_mut_parameter)]
    public entry fun update_exchange_rate<X: key + store, Y>(
        trade_pool: &mut trade_pool::TradePool<X, Y>,
        liquidity_token: &LiquidityToken<X, Y>,
        start_exchange_rate_numerator: u64,
        exchange_rate_numerator: u64,
        exchange_rate_denominator: u64,
        price_delta_x_amount: u64,
        price_delta_numerator: u64,
        price_delta_denominator: u64,
        ctx: &mut tx_context::TxContext,
    ) {
        trade_pool::assert_schema_version(trade_pool);
        let pool_exchange_rate_updated = trade_pool_update_exchange_rate_logic::verify<X, Y>(
            liquidity_token,
            start_exchange_rate_numerator,
            exchange_rate_numerator,
            exchange_rate_denominator,
            price_delta_x_amount,
            price_delta_numerator,
            price_delta_denominator,
            trade_pool,
            ctx,
        );
        trade_pool_update_exchange_rate_logic::mutate<X, Y>(
            &pool_exchange_rate_updated,
            trade_pool,
            ctx,
        );
        trade_pool::update_object_version(trade_pool);
        trade_pool::emit_pool_exchange_rate_updated(pool_exchange_rate_updated);
    }

    #[allow(unused_mut_parameter)]
    public(friend) fun add_x_token<X: key + store, Y>(
        trade_pool: &mut trade_pool::TradePool<X, Y>,
        liquidity_token: &LiquidityToken<X, Y>,
        x: X,
        x_amount: u64,
        ctx: &mut tx_context::TxContext,
    ) {
        trade_pool::assert_schema_version(trade_pool);
        let pool_x_token_added = trade_pool_add_x_token_logic::verify<X, Y>(
            liquidity_token,
            &x,
            x_amount,
            trade_pool,
            ctx,
        );
        trade_pool_add_x_token_logic::mutate<X, Y>(
            &pool_x_token_added,
            x,
            trade_pool,
            ctx,
        );
        trade_pool::update_object_version(trade_pool);
        trade_pool::emit_pool_x_token_added(pool_x_token_added);
    }

    #[allow(unused_mut_parameter)]
    public fun remove_x_token<X: key + store, Y>(
        trade_pool: &mut trade_pool::TradePool<X, Y>,
        liquidity_token: &LiquidityToken<X, Y>,
        x_id: ID,
        ctx: &mut tx_context::TxContext,
    ): X {
        trade_pool::assert_schema_version(trade_pool);
        let pool_x_token_removed = trade_pool_remove_x_token_logic::verify<X, Y>(
            liquidity_token,
            x_id,
            trade_pool,
            ctx,
        );
        let remove_x_token_return = trade_pool_remove_x_token_logic::mutate<X, Y>(
            &pool_x_token_removed,
            trade_pool,
            ctx,
        );
        trade_pool::update_object_version(trade_pool);
        trade_pool::emit_pool_x_token_removed(pool_x_token_removed);
        remove_x_token_return
    }

    #[allow(unused_mut_parameter)]
    public fun deposit_y_reserve<X: key + store, Y>(
        trade_pool: &mut trade_pool::TradePool<X, Y>,
        liquidity_token: &LiquidityToken<X, Y>,
        y_amount: Balance<Y>,
        ctx: &mut tx_context::TxContext,
    ) {
        trade_pool::assert_schema_version(trade_pool);
        let pool_y_reserve_deposited = trade_pool_deposit_y_reserve_logic::verify<X, Y>(
            liquidity_token,
            &y_amount,
            trade_pool,
            ctx,
        );
        trade_pool_deposit_y_reserve_logic::mutate<X, Y>(
            &pool_y_reserve_deposited,
            y_amount,
            trade_pool,
            ctx,
        );
        trade_pool::update_object_version(trade_pool);
        trade_pool::emit_pool_y_reserve_deposited(pool_y_reserve_deposited);
    }

    #[allow(unused_mut_parameter)]
    public fun withdraw_y_reserve<X: key + store, Y>(
        trade_pool: &mut trade_pool::TradePool<X, Y>,
        liquidity_token: &LiquidityToken<X, Y>,
        y_amount: u64,
        ctx: &mut tx_context::TxContext,
    ): Balance<Y> {
        trade_pool::assert_schema_version(trade_pool);
        let pool_y_reserve_withdrawn = trade_pool_withdraw_y_reserve_logic::verify<X, Y>(
            liquidity_token,
            y_amount,
            trade_pool,
            ctx,
        );
        let withdraw_y_reserve_return = trade_pool_withdraw_y_reserve_logic::mutate<X, Y>(
            &pool_y_reserve_withdrawn,
            trade_pool,
            ctx,
        );
        trade_pool::update_object_version(trade_pool);
        trade_pool::emit_pool_y_reserve_withdrawn(pool_y_reserve_withdrawn);
        withdraw_y_reserve_return
    }

    #[allow(unused_mut_parameter)]
    public entry fun destroy<X: key + store, Y>(
        trade_pool: trade_pool::TradePool<X, Y>,
        liquidity_token: &LiquidityToken<X, Y>,
        ctx: &mut tx_context::TxContext,
    ) {
        trade_pool::assert_schema_version(&trade_pool);
        let pool_destroyed = trade_pool_destroy_logic::verify<X, Y>(
            liquidity_token,
            &trade_pool,
            ctx,
        );
        let updated_trade_pool = trade_pool_destroy_logic::mutate<X, Y>(
            &pool_destroyed,
            trade_pool,
            ctx,
        );
        trade_pool::drop_trade_pool(updated_trade_pool);
        trade_pool::emit_pool_destroyed(pool_destroyed);
    }

    #[allow(unused_mut_parameter)]
    public fun buy_x<X: key + store, Y>(
        trade_pool: &mut trade_pool::TradePool<X, Y>,
        y_amount: Balance<Y>,
        x_id: ID,
        ctx: &mut tx_context::TxContext,
    ): X {
        trade_pool::assert_schema_version(trade_pool);
        let pool_y_swapped_for_x = trade_pool_buy_x_logic::verify<X, Y>(
            &y_amount,
            x_id,
            trade_pool,
            ctx,
        );
        let buy_x_return = trade_pool_buy_x_logic::mutate<X, Y>(
            &pool_y_swapped_for_x,
            y_amount,
            trade_pool,
            ctx,
        );
        trade_pool::update_object_version(trade_pool);
        trade_pool::emit_pool_y_swapped_for_x(pool_y_swapped_for_x);
        buy_x_return
    }

    #[allow(unused_mut_parameter)]
    public(friend) fun sell_x<X: key + store, Y>(
        trade_pool: &mut trade_pool::TradePool<X, Y>,
        x: X,
        x_amount: u64,
        expected_y_amount_out: u64,
        ctx: &mut tx_context::TxContext,
    ): Balance<Y> {
        trade_pool::assert_schema_version(trade_pool);
        let pool_x_swapped_for_y = trade_pool_sell_x_logic::verify<X, Y>(
            &x,
            x_amount,
            expected_y_amount_out,
            trade_pool,
            ctx,
        );
        let sell_x_return = trade_pool_sell_x_logic::mutate<X, Y>(
            &pool_x_swapped_for_y,
            x,
            trade_pool,
            ctx,
        );
        trade_pool::update_object_version(trade_pool);
        trade_pool::emit_pool_x_swapped_for_y(pool_x_swapped_for_y);
        sell_x_return
    }

}
