// <autogenerated>
//   This file was generated by dddappp code generator.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

module sui_swap_example::trade_pool_initialized {

    use std::option::{Self, Option};
    use std::string::String;
    use sui::object::{Self, ID};
    use sui_swap_example::trade_pool::{Self, TradePoolInitialized};

    public fun id(trade_pool_initialized: &TradePoolInitialized): option::Option<object::ID> {
        trade_pool::trade_pool_initialized_id(trade_pool_initialized)
    }

    public fun exchange_id(trade_pool_initialized: &TradePoolInitialized): ID {
        trade_pool::trade_pool_initialized_exchange_id(trade_pool_initialized)
    }

    public fun exchange_rate_numerator(trade_pool_initialized: &TradePoolInitialized): u64 {
        trade_pool::trade_pool_initialized_exchange_rate_numerator(trade_pool_initialized)
    }

    public fun exchange_rate_denominator(trade_pool_initialized: &TradePoolInitialized): u64 {
        trade_pool::trade_pool_initialized_exchange_rate_denominator(trade_pool_initialized)
    }

    public fun price_curve_type(trade_pool_initialized: &TradePoolInitialized): u8 {
        trade_pool::trade_pool_initialized_price_curve_type(trade_pool_initialized)
    }

    public fun price_delta_x_amount(trade_pool_initialized: &TradePoolInitialized): u64 {
        trade_pool::trade_pool_initialized_price_delta_x_amount(trade_pool_initialized)
    }

    public fun price_delta_numerator(trade_pool_initialized: &TradePoolInitialized): u64 {
        trade_pool::trade_pool_initialized_price_delta_numerator(trade_pool_initialized)
    }

    public fun price_delta_denominator(trade_pool_initialized: &TradePoolInitialized): u64 {
        trade_pool::trade_pool_initialized_price_delta_denominator(trade_pool_initialized)
    }

    public fun provider(trade_pool_initialized: &TradePoolInitialized): address {
        trade_pool::trade_pool_initialized_provider(trade_pool_initialized)
    }

    public fun x_token_type(trade_pool_initialized: &TradePoolInitialized): String {
        trade_pool::trade_pool_initialized_x_token_type(trade_pool_initialized)
    }

    public fun y_token_type(trade_pool_initialized: &TradePoolInitialized): String {
        trade_pool::trade_pool_initialized_y_token_type(trade_pool_initialized)
    }

    public fun x_amount(trade_pool_initialized: &TradePoolInitialized): u64 {
        trade_pool::trade_pool_initialized_x_amount(trade_pool_initialized)
    }

    public fun y_amount(trade_pool_initialized: &TradePoolInitialized): u64 {
        trade_pool::trade_pool_initialized_y_amount(trade_pool_initialized)
    }

    public fun liquidity_token_id(trade_pool_initialized: &TradePoolInitialized): Option<ID> {
        trade_pool::trade_pool_initialized_liquidity_token_id(trade_pool_initialized)
    }

    public fun x_id(trade_pool_initialized: &TradePoolInitialized): ID {
        trade_pool::trade_pool_initialized_x_id(trade_pool_initialized)
    }

}
