// <autogenerated>
//   This file was generated by dddappp code generator.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

module sui_swap_example::y_reserve_withdrawn {

    use std::string::String;
    use sui::object::{Self, ID};
    use sui_swap_example::sell_pool::{Self, YReserveWithdrawn};

    public fun id(y_reserve_withdrawn: &YReserveWithdrawn): object::ID {
        sell_pool::y_reserve_withdrawn_id(y_reserve_withdrawn)
    }

    public fun liquidity_token_id(y_reserve_withdrawn: &YReserveWithdrawn): ID {
        sell_pool::y_reserve_withdrawn_liquidity_token_id(y_reserve_withdrawn)
    }

    public fun y_amount(y_reserve_withdrawn: &YReserveWithdrawn): u64 {
        sell_pool::y_reserve_withdrawn_y_amount(y_reserve_withdrawn)
    }

    public fun x_token_type(y_reserve_withdrawn: &YReserveWithdrawn): String {
        sell_pool::y_reserve_withdrawn_x_token_type(y_reserve_withdrawn)
    }

    public fun y_token_type(y_reserve_withdrawn: &YReserveWithdrawn): String {
        sell_pool::y_reserve_withdrawn_y_token_type(y_reserve_withdrawn)
    }

}
