// <autogenerated>
//   This file was generated by dddappp code generator.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

module sui_swap_example::exchange_updated {

    use std::string::String;
    use sui::object::{Self, ID};
    use sui_swap_example::exchange::{Self, ExchangeUpdated};

    public fun id(exchange_updated: &ExchangeUpdated): object::ID {
        exchange::exchange_updated_id(exchange_updated)
    }

    public fun name(exchange_updated: &ExchangeUpdated): String {
        exchange::exchange_updated_name(exchange_updated)
    }

    public fun token_pairs(exchange_updated: &ExchangeUpdated): vector<ID> {
        exchange::exchange_updated_token_pairs(exchange_updated)
    }

    public fun x_token_types(exchange_updated: &ExchangeUpdated): vector<String> {
        exchange::exchange_updated_x_token_types(exchange_updated)
    }

    public fun y_token_types(exchange_updated: &ExchangeUpdated): vector<String> {
        exchange::exchange_updated_y_token_types(exchange_updated)
    }

}
