// <autogenerated>
//   This file was generated by dddappp code generator.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

module sui_swap_example::exchange_rate_updated {

    use std::string::String;
    use sui::object::{Self, ID};
    use sui_swap_example::token_pair::{Self, ExchangeRateUpdated};

    public fun id(exchange_rate_updated: &ExchangeRateUpdated): object::ID {
        token_pair::exchange_rate_updated_id(exchange_rate_updated)
    }

    public fun liquidity_token_id(exchange_rate_updated: &ExchangeRateUpdated): ID {
        token_pair::exchange_rate_updated_liquidity_token_id(exchange_rate_updated)
    }

    public fun exchange_rate_numerator(exchange_rate_updated: &ExchangeRateUpdated): u64 {
        token_pair::exchange_rate_updated_exchange_rate_numerator(exchange_rate_updated)
    }

    public fun exchange_rate_denominator(exchange_rate_updated: &ExchangeRateUpdated): u64 {
        token_pair::exchange_rate_updated_exchange_rate_denominator(exchange_rate_updated)
    }

    public fun provider(exchange_rate_updated: &ExchangeRateUpdated): address {
        token_pair::exchange_rate_updated_provider(exchange_rate_updated)
    }

    public fun x_token_type(exchange_rate_updated: &ExchangeRateUpdated): String {
        token_pair::exchange_rate_updated_x_token_type(exchange_rate_updated)
    }

    public fun y_token_type(exchange_rate_updated: &ExchangeRateUpdated): String {
        token_pair::exchange_rate_updated_y_token_type(exchange_rate_updated)
    }

}
