// <autogenerated>
//   This file was generated by dddappp code generator.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

module sui_swap_example::liquidity_token_minted {

    use std::option;
    use sui::object;
    use sui_swap_example::liquidity_token::{Self, LiquidityTokenMinted};

    public fun id(liquidity_token_minted: &LiquidityTokenMinted): option::Option<object::ID> {
        liquidity_token::liquidity_token_minted_id(liquidity_token_minted)
    }

    public fun amount(liquidity_token_minted: &LiquidityTokenMinted): u64 {
        liquidity_token::liquidity_token_minted_amount(liquidity_token_minted)
    }

}
