// <autogenerated>
//   This file was generated by dddappp code generator.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

module sui_swap_example::liquidity_token_split {

    use sui::object;
    use sui_swap_example::liquidity_token::{Self, LiquidityTokenSplit};

    public fun id(liquidity_token_split: &LiquidityTokenSplit): object::ID {
        liquidity_token::liquidity_token_split_id(liquidity_token_split)
    }

    public fun amount(liquidity_token_split: &LiquidityTokenSplit): u64 {
        liquidity_token::liquidity_token_split_amount(liquidity_token_split)
    }

}
