// <autogenerated>
//   This file was generated by dddappp code generator.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

module sui_swap_example::y_reserve_withdrawn {

    use std::string::String;
    use sui::object::{Self, ID};
    use sui_swap_example::token_pair::{Self, Y_ReserveWithdrawn};

    public fun id(y_reserve_withdrawn: &Y_ReserveWithdrawn): object::ID {
        token_pair::y_reserve_withdrawn_id(y_reserve_withdrawn)
    }

    public fun liquidity_token_id(y_reserve_withdrawn: &Y_ReserveWithdrawn): ID {
        token_pair::y_reserve_withdrawn_liquidity_token_id(y_reserve_withdrawn)
    }

    public fun y_amount(y_reserve_withdrawn: &Y_ReserveWithdrawn): u64 {
        token_pair::y_reserve_withdrawn_y_amount(y_reserve_withdrawn)
    }

    public fun x_token_type(y_reserve_withdrawn: &Y_ReserveWithdrawn): String {
        token_pair::y_reserve_withdrawn_x_token_type(y_reserve_withdrawn)
    }

    public fun y_token_type(y_reserve_withdrawn: &Y_ReserveWithdrawn): String {
        token_pair::y_reserve_withdrawn_y_token_type(y_reserve_withdrawn)
    }

}
