// <autogenerated>
//   This file was generated by dddappp code generator.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

module sui_swap_example::y_reserve_deposited {

    use std::string::String;
    use sui::object;
    use sui_swap_example::token_pair::{Self, Y_ReserveDeposited};

    public fun id(y_reserve_deposited: &Y_ReserveDeposited): object::ID {
        token_pair::y_reserve_deposited_id(y_reserve_deposited)
    }

    public fun provider(y_reserve_deposited: &Y_ReserveDeposited): address {
        token_pair::y_reserve_deposited_provider(y_reserve_deposited)
    }

    public fun x_token_type(y_reserve_deposited: &Y_ReserveDeposited): String {
        token_pair::y_reserve_deposited_x_token_type(y_reserve_deposited)
    }

    public fun y_token_type(y_reserve_deposited: &Y_ReserveDeposited): String {
        token_pair::y_reserve_deposited_y_token_type(y_reserve_deposited)
    }

    public fun y_amount(y_reserve_deposited: &Y_ReserveDeposited): u64 {
        token_pair::y_reserve_deposited_y_amount(y_reserve_deposited)
    }

}
