// <autogenerated>
//   This file was generated by dddappp code generator.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

module sui_swap_example::y_swapped_for_x {

    use std::string::String;
    use sui::object;
    use sui_swap_example::token_pair::{Self, YSwappedForX};

    public fun id(y_swapped_for_x: &YSwappedForX): object::ID {
        token_pair::y_swapped_for_x_id(y_swapped_for_x)
    }

    public fun sender(y_swapped_for_x: &YSwappedForX): address {
        token_pair::y_swapped_for_x_sender(y_swapped_for_x)
    }

    public fun x_token_type(y_swapped_for_x: &YSwappedForX): String {
        token_pair::y_swapped_for_x_x_token_type(y_swapped_for_x)
    }

    public fun y_token_type(y_swapped_for_x: &YSwappedForX): String {
        token_pair::y_swapped_for_x_y_token_type(y_swapped_for_x)
    }

    public fun x_amount(y_swapped_for_x: &YSwappedForX): u64 {
        token_pair::y_swapped_for_x_x_amount(y_swapped_for_x)
    }

    public fun y_amount(y_swapped_for_x: &YSwappedForX): u64 {
        token_pair::y_swapped_for_x_y_amount(y_swapped_for_x)
    }

}
