[package]
# Movement M2 devnet:
#published-at = "0xe51eeb52778b7fb4ae33ae206c2dc0440fe8e174324a01145b1bee5fef276fe9"
# Sui testnet:
published-at = "0x81ccbc687db60ddb6a87100e007396d71d85d41677305e70af7b91305ec5514b" # UPGRADED-PACKAGE-ID 3
#published-at = "0x93d594cf0e132c68fabce857b5abd89cdb7b34e27dcbd5a3c0dc809a0ffb3fea" # UPGRADED-PACKAGE-ID 2
#published-at = "0x9be6c08a00a0c42912f959c94a7f3a92f1cb6cd5dde5c8be8301c0bb7c49ceb1" # UPGRADED-PACKAGE-ID 1
#published-at = "0x4d6c3dd86aac1db8f2337fe78fb087ef5ea6812715edec09e4d9fa363872c261" # ORIGINAL-PACKAGE-ID
name = "sui_swap_core"
version = "0.0.1"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "framework/testnet" }
#Sui = { local = "../../../../MystenLabs/sui/crates/sui-framework/packages/sui-framework" }
sui_swap_utils = { local = "../utils" }

[addresses]
# Movement M2 devnet:
#sui_swap_core = "0xe51eeb52778b7fb4ae33ae206c2dc0440fe8e174324a01145b1bee5fef276fe9"
# Sui testnet:
sui_swap_core = "0x4d6c3dd86aac1db8f2337fe78fb087ef5ea6812715edec09e4d9fa363872c261" # ORIGINAL-PACKAGE-ID
#sui_swap_core = "0x0"
