[package]
name = "sui_swap_utils"
version = "0.0.1"
#published-at = "0xe36d537bbb7342557e0a9cdf5ed4a6372537fcec532ab2a0e9d3d1e733011963"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "framework/testnet" }
#Sui = { local = "../../../../MystenLabs/sui/crates/sui-framework/packages/sui-framework" }

[addresses]
sui_swap_utils = "0x0"
