[package]
published-at = "0x9815664745b59f0ab09f247bb196ce80d0f635aee403ed15216b163175f3a8bd"
name = "nft_service_impl"
version = "0.0.1"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "framework/testnet" }
#Sui = { local = "../../../MystenLabs/sui/crates/sui-framework/packages/sui-framework" }
SmartInscription = { local = "../../../../movescriptions/movescriptions/sui" }
sui_swap_core = { local = "../core" }
sui_swap_utils = { local = "../utils" }

[addresses]
nft_service_impl = "0x9815664745b59f0ab09f247bb196ce80d0f635aee403ed15216b163175f3a8bd"
#nft_service_impl = "0x0"
#sui = "0000000000000000000000000000000000000000000000000000000000000002"
