[package]
published-at = "0x5a73f6c254f726a1abdcfdb394d277b06e430868f5db77149a942d8a877f3b79"
name = "sui_swap_di"
version = "0.0.1"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "framework/testnet" }
#Sui = { local = "../../../MystenLabs/sui/crates/sui-framework/packages/sui-framework" }
SmartInscription = { local = "../../../../movescriptions/movescriptions/sui" }
sui_swap_core = { local = "../core" }
nft_service_impl = { local = "../nft-service-impl" }
sui_swap_utils = { local = "../utils" }

[addresses]
sui_swap_di = "0x5a73f6c254f726a1abdcfdb394d277b06e430868f5db77149a942d8a877f3b79"
#sui_swap_di = "0x0"
#sui = "0000000000000000000000000000000000000000000000000000000000000002"
